name: MeHu
favicon: null
layout_spectrum: 0.8368732915259898
typography_spectrum: 0.9953222696203738
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7696262365207076
  lightness: 0.5729618407785892
  saturation: 0.5411832069512457
  rhythmicContrast: 0.420516504207626
purpose: []
